// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace OctopusTest.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Checkboxes")]
    public partial class CheckboxesFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Checkboxes.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Checkboxes", "\tIn order to see employees only from a particular team(s)\r\n\tAs a website user\r\n\tI" +
                    " want to be able to use team filtering function", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
 #line 8
 testRunner.Given("I launch chrome", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Team"});
            table1.AddRow(new string[] {
                        "Anna Pollins",
                        "Strategic partnerships team"});
            table1.AddRow(new string[] {
                        "Charlotte Fairhurst",
                        "Strategic partnerships team"});
            table1.AddRow(new string[] {
                        "Matt Johnson",
                        "Strategic partnerships team"});
            table1.AddRow(new string[] {
                        "Nick Maidment",
                        "Strategic partnerships team"});
            table1.AddRow(new string[] {
                        "Steve Skelding",
                        "Strategic partnerships team"});
            table1.AddRow(new string[] {
                        "Emily James",
                        "Sales support team"});
            table1.AddRow(new string[] {
                        "Georgina Clark",
                        "Sales support team"});
            table1.AddRow(new string[] {
                        "Harriet Morton-Liddle",
                        "Sales support team"});
            table1.AddRow(new string[] {
                        "Louise Barelli",
                        "Sales support team"});
            table1.AddRow(new string[] {
                        "Oliver Wallin",
                        "Multi manager team"});
#line 10
 testRunner.And("I load employee teams data", ((string)(null)), table1, "And ");
#line 23
 testRunner.And("I navigate to Octopus home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
 testRunner.And("I maximise browser window", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.And("I navigate to Our People page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that when ticking a team and searching for an employee who is not in that " +
            "team, his/her name will not be returned")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void VerifyThatWhenTickingATeamAndSearchingForAnEmployeeWhoIsNotInThatTeamHisHerNameWillNotBeReturned()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that when ticking a team and searching for an employee who is not in that " +
                    "team, his/her name will not be returned", new string[] {
                        "mytag"});
#line 28
this.ScenarioSetup(scenarioInfo);
#line 7
 this.FeatureBackground();
#line 29
 testRunner.Given("I have ticked a team checkbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 30
 testRunner.And("I have entered 70 into the calculator", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.When("I press add", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 32
 testRunner.Then("the result should be 120 on the screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
