// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace OctopusTest.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("SearchBox")]
    public partial class SearchBoxFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SearchBox.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SearchBox", "\tIn order to reduce the list of employees\r\n\tAs a website visitor\r\n\tI want to use " +
                    "search box to look for employees of interest", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
 #line 7
 testRunner.Given("I launch chrome", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Team"});
            table1.AddRow(new string[] {
                        "Anna Pollins",
                        "Strategic partnerships team"});
            table1.AddRow(new string[] {
                        "Charlotte Fairhurst",
                        "Strategic partnerships team"});
            table1.AddRow(new string[] {
                        "Matt Johnson",
                        "Strategic partnerships team"});
            table1.AddRow(new string[] {
                        "Nick Maidment",
                        "Strategic partnerships team"});
            table1.AddRow(new string[] {
                        "Steve Skelding",
                        "Strategic partnerships team"});
            table1.AddRow(new string[] {
                        "Emily James",
                        "Sales support team"});
            table1.AddRow(new string[] {
                        "Georgina Clark",
                        "Sales support team"});
            table1.AddRow(new string[] {
                        "Harriet Morton-Liddle",
                        "Sales support team"});
            table1.AddRow(new string[] {
                        "Louise Barelli",
                        "Sales support team"});
            table1.AddRow(new string[] {
                        "Oliver Wallin",
                        "Multi manager team"});
#line 9
 testRunner.And("I load employee teams data", ((string)(null)), table1, "And ");
#line 22
 testRunner.And("I navigate to Octopus home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.And("I maximise browser window", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
 testRunner.And("I navigate to Our People page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search by typing full name")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void SearchByTypingFullName()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search by typing full name", new string[] {
                        "mytag"});
#line 28
this.ScenarioSetup(scenarioInfo);
#line 6
 this.FeatureBackground();
#line 29
 testRunner.Given("I type a person name in the searchbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 30
 testRunner.Then("person with such name appears on the screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search for invalid name")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void SearchForInvalidName()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search for invalid name", new string[] {
                        "mytag"});
#line 34
this.ScenarioSetup(scenarioInfo);
#line 6
 this.FeatureBackground();
#line 35
 testRunner.Given("I type a name that does not exist in Employees Table", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 36
 testRunner.Then("No Results text is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
